exposure:
  spacecraft_file: 'spacecraft.fits.gz'
  time_i: '2023-01-10 15:00:00.00' 
  time_f: '2023-01-10 15:00:01.00'

source:
  spectrum:
    class: PowerLawSpectralModel
    kwargs:
      index: 2.2
      amplitude: '1e-3 / (cm2 s keV)'
      reference: '100 keV'
  location:
    ra: '83.6330 deg'
    dec: '22.0144 deg'

